/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ReferenceCardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// data.ts
var DEFAULT_DATA = {
  cards: [],
  nextId: 1
};
function createEmptyCard(id) {
  return {
    id,
    title: "",
    tags: [],
    year: "",
    notes: ""
  };
}
function getAllTags(cards) {
  const tagSet = /* @__PURE__ */ new Set();
  for (const card of cards) {
    for (const tag of card.tags) {
      tagSet.add(tag);
    }
  }
  return Array.from(tagSet).sort();
}

// view.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE = "reference-cards-view";
var ReferenceCardView = class extends import_obsidian.ItemView {
  constructor(leaf, app, data, saveData, getLastMarkdownView, settings) {
    super(leaf);
    this.filterTag = "";
    this.saveTimeout = null;
    this.app = app;
    this.data = data;
    this.saveData = saveData;
    this.getLastMarkdownView = getLastMarkdownView;
    this.settings = settings;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Reference Cards";
  }
  getIcon() {
    return "file-text";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ref-cards-container");
    this.headerEl = container.createDiv({ cls: "ref-cards-header" });
    this.renderHeader();
    this.cardContainer = container.createDiv({ cls: "ref-cards-list" });
    this.renderCards();
  }
  async onClose() {
  }
  renderHeader() {
    this.headerEl.empty();
    const addBtn = this.headerEl.createEl("button", { cls: "ref-cards-add-btn", text: "+" });
    addBtn.addEventListener("click", () => this.addCard());
    const filterSelect = this.headerEl.createEl("select", { cls: "ref-cards-filter" });
    const allTags = getAllTags(this.data.cards);
    filterSelect.createEl("option", { text: "All tags", value: "" });
    for (const tag of allTags) {
      filterSelect.createEl("option", { text: tag, value: tag });
    }
    filterSelect.value = this.filterTag;
    filterSelect.addEventListener("change", () => {
      this.filterTag = filterSelect.value;
      this.renderCards();
    });
  }
  renderCards() {
    this.cardContainer.empty();
    const filtered = this.filterTag ? this.data.cards.filter((c) => c.tags.includes(this.filterTag)) : this.data.cards;
    for (const card of filtered) {
      this.renderCard(card);
    }
  }
  renderCard(card) {
    const cardEl = this.cardContainer.createDiv({ cls: "ref-card", attr: { "data-card-id": String(card.id) } });
    const topRow = cardEl.createDiv({ cls: "ref-card-top" });
    const idBadge = topRow.createSpan({ cls: "ref-card-id", text: `[${card.id}]` });
    const titleInput = topRow.createDiv({
      cls: "ref-card-title-input" + (this.settings.titleSoftWrap ? " ref-card-title-softwrap" : ""),
      attr: { "data-placeholder": "Title..." }
    });
    titleInput.contentEditable = "true";
    titleInput.textContent = card.title;
    titleInput.addEventListener("input", () => {
      card.title = titleInput.textContent || "";
      this.debouncedSave();
    });
    const insertBtn = topRow.createEl("button", { cls: "ref-card-insert-btn", text: "+" });
    insertBtn.title = "Insert reference at cursor";
    insertBtn.addEventListener("click", () => this.insertReference(card.id));
    const deleteBtn = topRow.createEl("button", { cls: "ref-card-delete-btn", text: "\xD7" });
    deleteBtn.title = "Delete card";
    deleteBtn.addEventListener("click", () => this.deleteCard(card.id));
    const tagsRow = cardEl.createDiv({ cls: "ref-card-tags" });
    tagsRow.createSpan({ cls: "ref-card-label", text: "Tags:" });
    const tagsInput = tagsRow.createEl("input", {
      cls: "ref-card-tags-input",
      attr: { type: "text", placeholder: "comma, separated" }
    });
    tagsInput.value = card.tags.join(", ");
    tagsInput.addEventListener("input", () => {
      card.tags = tagsInput.value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
      this.debouncedSave();
    });
    tagsInput.addEventListener("change", () => {
      this.renderHeader();
    });
    const yearRow = cardEl.createDiv({ cls: "ref-card-year" });
    yearRow.createSpan({ cls: "ref-card-label", text: "Year:" });
    const yearInput = yearRow.createEl("input", {
      cls: "ref-card-year-input",
      attr: { type: "text", placeholder: "e.g. 2024" }
    });
    yearInput.value = card.year;
    yearInput.addEventListener("input", () => {
      card.year = yearInput.value;
      this.debouncedSave();
    });
    const notesArea = cardEl.createEl("textarea", {
      cls: "ref-card-notes",
      attr: { placeholder: "Notes..." }
    });
    notesArea.value = card.notes;
    notesArea.addEventListener("input", () => {
      card.notes = notesArea.value;
      this.resizeTextarea(notesArea);
      this.debouncedSave();
    });
    this.resizeTextarea(notesArea);
  }
  resizeTextarea(textarea) {
    textarea.style.height = "auto";
    textarea.style.height = textarea.scrollHeight + "px";
  }
  debouncedSave() {
    if (this.saveTimeout)
      clearTimeout(this.saveTimeout);
    this.saveTimeout = setTimeout(() => {
      this.saveData();
    }, 500);
  }
  async addCard() {
    const card = createEmptyCard(this.data.nextId++);
    this.data.cards.push(card);
    await this.saveData();
    this.renderCards();
    this.renderHeader();
    const cardEl = this.cardContainer.querySelector(`[data-card-id="${card.id}"]`);
    if (cardEl) {
      cardEl.scrollIntoView({ behavior: "smooth", block: "center" });
      const titleInput = cardEl.querySelector(".ref-card-title-input");
      if (titleInput)
        titleInput.focus();
    }
  }
  async deleteCard(id) {
    this.data.cards = this.data.cards.filter((c) => c.id !== id);
    await this.saveData();
    this.renderCards();
    this.renderHeader();
  }
  insertReference(id) {
    const mdView = this.getLastMarkdownView();
    if (!mdView)
      return;
    const editor = mdView.editor;
    const cursor = editor.getCursor();
    editor.replaceRange(`{${id}}`, cursor);
    editor.setCursor({ line: cursor.line, ch: cursor.ch + String(id).length + 2 });
  }
  scrollToCard(id) {
    const card = this.data.cards.find((c) => c.id === id);
    if (!card)
      return;
    if (this.filterTag && !card.tags.includes(this.filterTag)) {
      this.filterTag = "";
      this.renderCards();
      this.renderHeader();
    }
    const cardEl = this.cardContainer.querySelector(`[data-card-id="${id}"]`);
    if (!cardEl)
      return;
    cardEl.scrollIntoView({ behavior: "smooth", block: "center" });
    cardEl.removeClass("ref-card-highlight");
    void cardEl.offsetWidth;
    cardEl.addClass("ref-card-highlight");
    setTimeout(() => {
      cardEl.removeClass("ref-card-highlight");
    }, 2e3);
  }
  updateData(data) {
    this.data = data;
  }
  renderAll() {
    this.renderHeader();
    this.renderCards();
  }
};

// editor-plugin.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var REF_REGEX = /\{(\d+)\}/g;
function buildDecorations(view) {
  const builder = new import_state.RangeSetBuilder();
  for (const { from, to } of view.visibleRanges) {
    const text = view.state.doc.sliceString(from, to);
    let match;
    REF_REGEX.lastIndex = 0;
    while ((match = REF_REGEX.exec(text)) !== null) {
      const start = from + match.index;
      const end = start + match[0].length;
      builder.add(start, end, import_view.Decoration.mark({ class: "ref-card-link" }));
    }
  }
  return builder.finish();
}
function createEditorPlugin(onNavigate) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = buildDecorations(view);
        this.editorDom = view.dom;
        this.clickHandler = (e) => {
          const el = e.target.closest(".ref-card-link");
          if (!el)
            return;
          const m = (el.textContent || "").match(/\{(\d+)\}/);
          if (m)
            onNavigate(parseInt(m[1], 10));
        };
        this.editorDom.addEventListener("click", this.clickHandler);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = buildDecorations(update.view);
        }
      }
      destroy() {
        this.editorDom.removeEventListener("click", this.clickHandler);
      }
    },
    { decorations: (v) => v.decorations }
  );
}

// settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  titleSoftWrap: true
};
var ReferenceCardsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Title soft wrap").setDesc("Allow long titles to wrap across multiple lines.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.titleSoftWrap).onChange(async (value) => {
        this.plugin.settings.titleSoftWrap = value;
        await this.plugin.saveSettings();
        this.plugin.refreshView();
      })
    );
  }
};

// main.ts
var ReferenceCardsPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
    this.lastMarkdownView = null;
  }
  async onload() {
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadSettings());
    this.addSettingTab(new ReferenceCardsSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian3.MarkdownView) {
          this.lastMarkdownView = leaf.view;
        }
      })
    );
    this.registerView(VIEW_TYPE, (leaf) => {
      this.view = new ReferenceCardView(
        leaf,
        this.app,
        this.data,
        () => this.savePluginData(),
        () => this.lastMarkdownView,
        this.settings
      );
      return this.view;
    });
    this.addRibbonIcon("file-text", "Reference Cards", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-reference-cards",
      name: "Open Reference Cards",
      callback: () => this.activateView()
    });
    const editorPlugin = createEditorPlugin((id) => {
      this.activateView().then(() => {
        if (this.view) {
          this.view.scrollToCard(id);
        }
      });
    });
    this.registerEditorExtension(editorPlugin);
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  refreshView() {
    if (this.view) {
      this.view.renderAll();
    }
  }
  async loadSettings() {
    return Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async savePluginData() {
    await this.saveData(this.data);
  }
};
